// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxwzbsrrbxwkjetwsmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeHd6YnNycmJ4d2tqZXR3c21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjE2MDIsImV4cCI6MjA2Mjk5NzYwMn0.qCCc3eUcXyKKeZ1haJu_Iz6O41qzUxImC9t-EdRsYqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);